use_frameworks!

platform :ios, '10.0'

target 'GCDWebsocketServer_Example' do
  pod 'GCDWebsocketServer', :path => '../'

  target 'GCDWebsocketServer_Tests' do
    inherit! :search_paths

    
  end
end
